#eureka的注册中心
eureka:
  client:
   service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
#虚拟主机名
# instance:
#    hostname: Client2
#应用名
spring:
  application:
    name: cloud-order
  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#数据源
#  datasource:
#    url: jdbc:mysql://192.168.200.136:3306/cloud_order?characterEncoding=utf-8&useSSL=false
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root
#  jpa:
#    show-sql: true
#服务器开启端口
#jdbc.className=com.mysql.jdbc.Driver
#jdbc.masterUrl=jdbc:mysql://192.168.200.136:3306/cloud_order?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#jdbc.slaveUrl=jdbc:mysql://192.168.200.137:3306/cloud_order?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#jdbc.username=root
#jdbc.password=root
jdbc:
   className: com.mysql.jdbc.Driver
   masterUrl: jdbc:mysql://192.168.200.136:3306/cloud_order?useUnicode=true&characterEncoding=UTF-8&useSSL=false
   slaveUrl: jdbc:mysql://192.168.200.137:3306/cloud_order?useUnicode=true&characterEncoding=UTF-8&useSSL=false
   username: root
   password: root
server:
  port: 8081
