#eureka的注册中心
eureka:
  client:
   service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
#虚拟主机名
# instance:
#    hostname: Client2
#应用名
spring:
  application:
    name: order
  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: '{cipher}dff2f73976fc1b053b3a9f3abeb1f2623a8672ff5c740200fd0fd7879eddfd2a'
  jpa:
    show-sql: true
#服务器开启端口
server:
  port: 8082
